version: '3.8'

services:
  backend:
    build: .
    command: >
      sh -c "./entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    networks:
      - backendnet

networks:
  backendnet:
    external: false